; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "InfoMensajero"
#define MyAppVersion "1.4"
#define MyAppPublisher "CIBERTEC.ORG"
#define MyAppURL "https://www.cibertec.org/"
#define MyAppExeName "InfoMensajero.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{F6CAE84B-D6C8-44EF-A777-DD2DD89FF24E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=LICENSE
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=Output
OutputBaseFilename=InfoMensajero
SetupIconFile=assets\icon.ico
SolidCompression=yes
WizardStyle=modern
WizardImageFile=assets\ECF0F1.png
WizardSmallImageFile=assets\ECF0F1.png

[Code]
function GetExistingDir(): String;
var
  existingPath: String;
begin
  Result := '';
  if RegQueryStringValue(HKEY_LOCAL_MACHINE, 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{#SetupSetting("AppId")}_is1', 'Inno Setup: App Path', existingPath) then
  begin
    Result := existingPath;
  end
  else if RegQueryStringValue(HKEY_CURRENT_USER, 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{#SetupSetting("AppId")}_is1', 'Inno Setup: App Path', existingPath) then
  begin
    Result := existingPath;
  end;
end;

function IsUpgrade(): Boolean;
begin
  Result := (GetExistingDir() <> '');
end;

function InitializeSetup(): Boolean;
var
  ExistingPath: String;
begin
  // Check if we are upgrading
  if IsUpgrade() then
  begin
    // Get the existing installation path
    ExistingPath := GetExistingDir();
    MsgBox('Se ha detectado una versión anterior de ' + '{#MyAppName}' + ' en ' + ExistingPath + '.'#13#10#13#10'El programa de instalación la actualizará a la versión ' + '{#MyAppVersion}' + '.', mbInformation, MB_OK);
  end;
  Result := True;
end;

[Languages]
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "assets\*"; DestDir: "{app}\assets"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "LICENSE"; DestDir: "{app}"; Flags: ignoreversion
Source: "README.md"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent